-- task_4.sql
USE alx_book_store;
SELECT INFORMATION_SCHEMA.COLUMNS, COLUMN_NAME, COLUMN_TYPE FROM Books;
FROM INFORMATION_SCHEMA.COLUMNS
"TABLE_SCHEMA = 'alx_book_store'", "TABLE_NAME = 'Books'"





